export const SOURCE_ICON: Record<string, string> = {
  all: "mdi-menu",
  total: "mdi-menu",
  formed: "mdi-web",
  socmed: "tabler-heart",
  news: "mdi-earth",
  media_cetak: "mdi-newspaper-variant-multiple",
  media_tv: "mdi-television",
  radio: "mdi-radio",
  running_text: "tabler-align-box-left-middle",
  twitter: "tabler-brand-x",
  facebook: "mdi-facebook",
  instagram: "mdi-instagram",
  youtube: "mdi-youtube",
  tiktok: "tabler-brand-tiktok",
  linkedin: "mdi-linkedin",
  forum: "mdi-forum",
  blog: "mdi-rss-box",
  review: "tabler-device-mobile-message",
};

export const SOURCE_NAME: Record<string, string> = {
//   all: handlerBilingual('global.all'),
//   total: handlerBilingual('global.all'),
//   formed: handlerBilingual('global.medkon'),
//   socmed: handlerBilingual('global.medsos'),
//   news: handlerBilingual('global.online-media'),
//   media_cetak: handlerBilingual('global.print-media'),
//   media_tv: handlerBilingual('global.tv-media'),
//   radio: handlerBilingual('global.radio'),
//   running_text: handlerBilingual('global.running-text'),
  twitter: "X",
  facebook: "Facebook",
  instagram: "Instagram",
  youtube: "Youtube",
  tiktok: "Tiktok",
  linkedin: "Linkedin",
  forum: "Forum",
  blog: "Blog",
  review: "Review Apps",
};

export const SOURCE_COLOR: Record<string, string> = {
  all: "#BDBDBD",
  total: "#2092EC",
  formed: "#28C76F",
  socmed: "#FF1744",
  news: "#00E676",
  media_cetak: "#A1887F",
  media_tv: "#FF1744",
  radio: "#FFEB3B",
  running_text: "#BA68C8",
  twitter: "#050505",
  facebook: "#1565C0",
  instagram: "#E040FB",
  youtube: "#FF0000",
  tiktok: "#1DE9B6",
  linkedin: "#FF9800",
  forum: "#607D8B",
  blog: "#FFEE58",
  review: "#40C4FF",
};
